#!/bin/bash

echo "=========================================================================="
printf "%-50s %-12s %-35s\n" "DEFAULT FIREWALL SERVICES" "STATUS" "DESCRIPTION"
echo "=========================================================================="

systemctl list-units --type=service --all --no-pager | grep -E 'firewall|firewalld|ufw|nft|iptables|csf|lfd|apf|ferm|shorewall|imunify360-agent.service' | grep -v -E 'sf-whm-|not-found|masked|imunify360-resource-unlock|failed' | awk '{print $1,$3,$5" "$6}' | sort -k2,2 | awk '{printf "%-50s %-12s %-35s\n",$1,$2,$3" "$4}'

echo ""
echo "=========================================================================="
printf "%-50s %-12s %-35s\n" "SERVERFREAK FIREWALL" "STATUS" "DESCRIPTION"
echo "=========================================================================="

SFWHM=$(systemctl list-units --type=service --all --no-pager | grep -E 'sf-whm-' | grep -v -E 'not-found|masked' | awk '{print $1,$3,$5" "$6}' | sort -k2,2)

if [ -n "$SFWHM" ]; then
    echo "$SFWHM" | awk '{printf "%-50s %-12s %-35s\n",$1,$2,$3" "$4}'
else
    printf "%-50s\n" "                                  NONE                                  " 
fi

echo "==========================================================================" 
