#!/bin/bash

if [ -f /usr/local/bin/firewall-check ]; then
    rm -f /usr/local/bin/firewall-check
else
    echo "firewall-check not found"
fi

if [ -f /usr/local/bin/firewall-check-remove ]; then
    rm -f /usr/local/bin/firewall-check-remove
    echo
    echo "firewall-check Removed"
fi
